#
b C:\Users\User\Documents\AulasProgres\BancoDados\
#
d "Schema Area":6,32;1 C:\Users\User\Documents\AulasProgres\BancoDados\
#
d "Employee":7,32;1 C:\Users\User\Documents\AulasProgres\BancoDados\ f 320
d "Employee":7,32;1 C:\Users\User\Documents\AulasProgres\BancoDados\
#
d "Inventory":8,32;1 C:\Users\User\Documents\AulasProgres\BancoDados\ f 640
d "Inventory":8,32;1 C:\Users\User\Documents\AulasProgres\BancoDados\
#
d "Cust_Data":9,32;1 C:\Users\User\Documents\AulasProgres\BancoDados\ f 320
d "Cust_Data":9,32;1 C:\Users\User\Documents\AulasProgres\BancoDados\
#
d "Cust_Index":10,32;1 C:\Users\User\Documents\AulasProgres\BancoDados\ f 320
d "Cust_Index":10,32;1 C:\Users\User\Documents\AulasProgres\BancoDados\
#
d "Order":11,32;1 C:\Users\User\Documents\AulasProgres\BancoDados\ f 1280
d "Order":11,32;1 C:\Users\User\Documents\AulasProgres\BancoDados\
#
d "Misc":12,32;1 C:\Users\User\Documents\AulasProgres\BancoDados\ f 320
d "Misc":12,32;1 C:\Users\User\Documents\AulasProgres\BancoDados\
