#
b !"\\br02\USUARIOS\boliveira\Meus Documentos\Banco Teste\"
#
d "Schema Area":6,32;1 !"\\br02\USUARIOS\boliveira\Meus Documentos\Banco Teste\"
#
d "Employee":7,32;1 !"\\br02\USUARIOS\boliveira\Meus Documentos\Banco Teste\" f 320
d "Employee":7,32;1 !"\\br02\USUARIOS\boliveira\Meus Documentos\Banco Teste\"
#
d "Inventory":8,32;1 !"\\br02\USUARIOS\boliveira\Meus Documentos\Banco Teste\" f 640
d "Inventory":8,32;1 !"\\br02\USUARIOS\boliveira\Meus Documentos\Banco Teste\"
#
d "Cust_Data":9,32;1 !"\\br02\USUARIOS\boliveira\Meus Documentos\Banco Teste\" f 320
d "Cust_Data":9,32;1 !"\\br02\USUARIOS\boliveira\Meus Documentos\Banco Teste\"
#
d "Cust_Index":10,32;1 !"\\br02\USUARIOS\boliveira\Meus Documentos\Banco Teste\" f 320
d "Cust_Index":10,32;1 !"\\br02\USUARIOS\boliveira\Meus Documentos\Banco Teste\"
#
d "Order":11,32;1 !"\\br02\USUARIOS\boliveira\Meus Documentos\Banco Teste\" f 1280
d "Order":11,32;1 !"\\br02\USUARIOS\boliveira\Meus Documentos\Banco Teste\"
#
d "Misc":12,32;1 !"\\br02\USUARIOS\boliveira\Meus Documentos\Banco Teste\" f 320
d "Misc":12,32;1 !"\\br02\USUARIOS\boliveira\Meus Documentos\Banco Teste\"
